// src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue'
import About from './components/About.vue'
import GitHubProjects from './components/GitHubProjects.vue'
import Skills from './components/Skills.vue'
import PixelAssistant from './components/PixelAssistant.vue'
// import Projects from './components/Projects.vue'
// import Contact from './components/Contact.vue'
import Footer from './components/Footer.vue'
import SpaceScene from './components/SpaceScene.vue'
import CookieBanner from './components/CookieBanner.vue'
</script>

<template>
  <div class="w-full max-w-[1400px] mx-auto">
    <Header />
    <SpaceScene />
    <About />
    <GitHubProjects />
    <Skills />
    <PixelAssistant />
    <!--
      <Projects /> 
      <Contact />
    -->
    <Footer />
    <CookieBanner />
  </div>
</template>

// src/app/page.tsx
import Header from "@/components/Header";
import SpaceScene from "@/components/SpaceScene";
import ScrollProgress from "@/components/ScrollProgress";
import FeaturedProjects from "@/components/FeaturedProjects";
import CaseHighlight from "@/components/CaseHighlight";
import Process from "@/components/Process";
import About from "@/components/About";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import HudBadge from "@/components/HudBadge";
import PixelSeparator from "@/components/PixelSeparator";
import CookieBanner from "@/components/CookieBanner";

export default function Home() {
  return (
    <div className="w-full">
      <ScrollProgress />
      <Header />
      <SpaceScene />
      <PixelSeparator />
      <FeaturedProjects />
      <PixelSeparator />
      <CaseHighlight />
      <PixelSeparator />
      <Process />
      <PixelSeparator />
      <About />
      <PixelSeparator />
      <Contact />
      <Footer />
      <HudBadge />
      <CookieBanner />
    </div>
  );
}
